version: '3'

services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:latest
    ports:
      - "4369:4369"
      - "5671-5672:5671-5672"
      - "15672:15672"
      - "25672:25672"
    healthcheck:
      test: ["CMD-SHELL", "if rabbitmqctl status; then \nexit 0 \nfi \nexit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongo",  "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5