server:
  port: 8081

logging:
  level:
    org.hibernate.type.descriptor.sql: TRACE
    io.myrecipes.api.mapper: TRACE
    io.myrecipes.api.controller: TRACE

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/myrecipe?serverTimezone=Asia/Seoul&useSSL=false
    username: mruser
    password: P@ssw0rd!
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: false

mybatis:
  type-aliases-package: io.myrecipes.api.model
