spring:
  profiles:
    active: local

app:
  artifactId: @project.artifactId@

server:
  port: 8081

---
spring:
  profiles: local
  http:
    encoding:
      force: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/myrecipes?serverTimezone=Asia/Seoul&useSSL=false
    username: mruser
    password: P@ssw0rd!
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: false
  cache:
    type: redis
    redis:
      time-to-live: 50000
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: mruser
    password: qwer1234!

logging:
  level:
    org.hibernate.type.descriptor.sql: TRACE
    #    link.myrecipes.api.mapper: TRACE
    org.springframework.web: TRACE

app:
  rabbitmq:
    exchange: logger.exchange
    routing:
      call: logger.controller.call
      fail: logger.controller.fail

---
spring:
  profiles: dev
  http:
    encoding:
      force: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://myrecipes-dev.cwnkdef17vae.ap-northeast-2.rds.amazonaws.com/myrecipes?serverTimezone=Asia/Seoul&useSSL=false
    username: mruser
    password: P@ssw0rd!
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: false
  cache:
    type: redis
    redis:
      time-to-live: 50000
  redis:
    host: 10.0.10.206
    port: 6379
  rabbitmq:
    host: 10.0.10.206
    port: 5672
    username: mruser
    password: qwer1234!

logging:
  level:
    org.hibernate.type.descriptor.sql: TRACE
    #    link.myrecipes.api.mapper: TRACE
    org.springframework.web: TRACE

---
spring:
  profiles: prod
  http:
    encoding:
      force: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://myrecipes-dev.cwnkdef17vae.ap-northeast-2.rds.amazonaws.com/myrecipes?serverTimezone=Asia/Seoul&useSSL=false
    username: mruser
    password: P@ssw0rd!
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: false
  cache:
    type: redis
    redis:
      time-to-live: 5000
  redis:
    host: 10.0.10.206
    port: 6379
  rabbitmq:
    host: 10.0.10.206
    port: 5672
    username: mruser
    password: qwer1234!

logging:
  level:
    org.hibernate.type.descriptor.sql: TRACE
    #    link.myrecipes.api.mapper: TRACE
    org.springframework.web: TRACE
