spring:
  profiles:
    active: local

app:
  artifactId: @project.artifactId@

server:
  port: 8081

---
spring:
  profiles: local
  http:
    encoding:
      force: true
  devtools:
    livereload:
      enabled: true
      port: 35731
    restart:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/myrecipes?serverTimezone=Asia/Seoul&useSSL=false
    username: mruser
    password: qwer1234!
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: false
  cache:
    type: redis
    redis:
      time-to-live: 50000
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: mruser
    password: qwer1234!
  data:
    mongodb:
      uri: mongodb://localhost:27017/myrecipes

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: TRACE

app:
  rabbitmq:
    exchange: logger.exchange
    routing:
      call: logger.controller.call
      fail: logger.controller.fail

---
spring:
  profiles: test
  http:
    encoding:
      force: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: false
  cache:
    type: redis
    redis:
      time-to-live: 50000
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: mruser
    password: qwer1234!
  data:
    mongodb:
      uri: mongodb://localhost:27017/myrecipes

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: TRACE

app:
  rabbitmq:
    exchange: logger.exchange
    routing:
      call: logger.controller.call
      fail: logger.controller.fail

---
spring:
  profiles: prod
  http:
    encoding:
      force: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.0.10.206/myrecipes?serverTimezone=Asia/Seoul&useSSL=false
    username: mruser
    password: qwer1234!
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: false
  cache:
    type: redis
    redis:
      time-to-live: 50000
  redis:
    host: 10.0.10.206
    port: 6379
  rabbitmq:
    host: 10.0.10.206
    port: 5672
    username: mruser
    password: qwer1234!
  data:
    mongodb:
      uri: mongodb://10.0.10.206:27017/myrecipes
      username: mruser
      password: qwer1234!

logging:
  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: TRACE

app:
  rabbitmq:
    exchange: logger.exchange
    routing:
      call: logger.controller.call
      fail: logger.controller.fail