spring:
  profiles:
    active: local

server:
  port: 8081

---
spring:
  profiles: local
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/myrecipes?serverTimezone=Asia/Seoul&useSSL=false
    username: mruser
    password: P@ssw0rd!
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: false
  cache:
    type: redis
    redis:
      time-to-live: 50000
  redis:
    host: localhost
    port: 6379

logging:
  level:
    org.hibernate.type.descriptor.sql: TRACE
    #    io.myrecipes.api.mapper: TRACE
    org.springframework.web: TRACE

---
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://myrecipes-dev.cwnkdef17vae.ap-northeast-2.rds.amazonaws.com/myrecipes?serverTimezone=Asia/Seoul&useSSL=false
    username: mruser
    password: P@ssw0rd!
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: false
  cache:
    type: redis
    redis:
      time-to-live: 50000
  redis:
    host: localhost
    port: 6379

logging:
  level:
    org.hibernate.type.descriptor.sql: TRACE
    io.myrecipes.api.mapper: TRACE
    io.myrecipes.api.controller: TRACE

---
spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://myrecipes-dev.cwnkdef17vae.ap-northeast-2.rds.amazonaws.com/myrecipes?serverTimezone=Asia/Seoul&useSSL=false
    username: mruser
    password: P@ssw0rd!
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: false
  cache:
    type: redis
    redis:
      time-to-live: 5000
  redis:
    host: localhost
    port: 6379

logging:
  level:
    org.hibernate.type.descriptor.sql: TRACE
    io.myrecipes.api.mapper: TRACE
    io.myrecipes.api.controller: TRACE
